relaycc/relay

src/components/pages/Profile.tsx
Closes https://github.com/relaycc/relay/issues/10
This solves the problem, but would take a sr dev to make sure it isn't causing security risks. I looked into it, don't think it does.
=> New links will open in different tabs

src/pages/_app.tsx
closes https://github.com/relaycc/relay/issues/5
=> Removing deprecated testnets from network switch

src/pages/_app.tsx, src/pages/u/[handle].tsx
Closes https://github.com/relaycc/relay/issues/2
=> When you navigate to a profile, the page title should show their handle.

public/lens.ts
Closes https://github.com/relaycc/relay/issues/60
=> typo in pharver was switched to phaver.lens

src/components/Footer.tsx
Closes https://github.com/relaycc/relay/issues/62
=> Scale footer for mobile views

public/defi.ts
=> Defi section update

src/components/cards/AppCard.tsx
PR for https://github.com/relaycc/relay/issues/106
Making sure Gamma swap is center aligned
=> make sure all of the cards are centered

src/lib/design/BackIcon.tsx
=> Implement back icon

src/lib/design/DropdownIcon.tsx
=> Implement dropdown icon

src/lib/design/Compose.tsx
=> Implement compose icon

src/lib/design/LogoutIcon.tsx
=> Implement logout icon

src/lib/design/LinkIcon.tsx
=> Implement link icon

src/lib/design/ProfileIcon.tsx
=> Implement profile icon

src/lib/design/Edit.tsx
=> Implement edit icon

src/lib/design/Copy.tsx, src/pages/receiver/messages.tsx
https://www.figma.com/file/oeHqO9qLCkz7SYb73J5Qx4/Receiver-Design-File?node-id=435%3A10172&t=ObvQU0nsa8ObgCMQ-0
https://github.com/relaycc/relay/issues/133
=> Implement copy icon

src/lib/design/StatusIcon.tsx
=> Implemented status icon

src/lib/design/RemoveIcon.tsx, src/lib/design/RestoreIcon.tsx
=> Implemented remove (restore) icon

src/lib/design/Close.tsx, src/lib/design/CloseIcon.tsx
=> Implemented close icon

src/lib/design/Checkbox.tsx
=> Implemented checkbox

src/lib/design/NewMsgInput.tsx
=> Implementing new msg input component

src/lib/design/ArrowUpCircle.tsx, src/lib/design/MsgBox.tsx
=> Implementing message box

src/lib/design/NewUserMessage.tsx, src/lib/design/PlusCircle.tsx
Closes #182 
Loom video: [loom](https://www.loom.com/share/46744326ab364f8db05dbf38a5339df2)
=> Implement new user message

src/lib/design/MsgBundlesReceived.tsx, src/lib/design/MsgBundlesSent.tsx
Issue #165
waiting for the StatusIcon to be put on(?) the develop branch
Loom video
https://www.loom.com/share/1e5da8ad870b441d92f1add1f62728bb
=> Implementing Msg bundles (v2)

src/lib/design/Copy.tsx
This component was developed before the loading states, so one I'll implement one on Copy.tsx
Per the Figma file
=> Loading state added to Copy-tsx

src/lib/design/Magnifier.tsx, src/lib/design/Search.tsx
=> Implemented search bar

src/lib/design/InfoToast.tsx, src/lib/design/InfoToastIcon.tsx
=> Implement InfoToast

src/lib/design/NewMsgHeader.tsx
=> Implemented new msg header

src/lib/design/MsgPreview.tsx
=> Implemented msg preview

src/lib/design/HomeHeader.tsx
=> Implemented home header

src/components/index.ts, src/lib/design/Badge.tsx, src/lib/design/ENSID.tsx
=> fixed Badge based on figma changes

src/lib/design/NewDateDivider.tsx
=> New Date Divider implementation

src/components/index.ts, src/lib/design/ENSName.tsx
=> Fixed ENS name  (truncating allowed)

src/components/index.ts, src/lib/design/ButtonView.tsx
=> Fixing button component to match design

src/components/index.ts, src/lib/design/XmtpStatus.tsx
=> Implement XMTP status

src/components/index.ts, src/lib/design/ENSName.tsx, src/lib/design/MsgBundlesReceived.tsx, src/lib/design/MsgBundlesSent.tsx, src/lib/design/Time.tsx
=> changed msg bundles' hover state

src/components/index.ts, src/lib/design/Chat.tsx, src/lib/design/PinButton.tsx, src/lib/design/PinIcon.tsx
=> Implementing Chat

src/components/NewMessage.tsx, src/design/MsgBox.tsx
=> MsgBox fix + implemented into the NewMessage page

package-lock.json, src/design/AddressHeader.tsx, src/design/Badge.tsx, src/design/DMHeader.tsx, src/design/ENSID.tsx, src/design/HeaderRequests.tsx, src/design/IgnoredMsg.tsx, src/design/InfoToast.tsx, src/design/XmtpStatus.tsx, src/pages/design/index.tsx, src/pages/receiver/profile.tsx, src/pages/receiver/sign.tsx
Closes #274 
Closes #276 
Closes #277 
Closes #279
Closes #280
Closes #281
=> Fix components to match with design system

src/design/Badge.tsx, src/pages/receiver/profile.tsx
=> Fix badge returns and styles

src/design/NewDateDivider.tsx
=> Fixed new date divider element

src/components/MessagesPage.tsx, src/components/NewMessage.tsx, src/design/Compose.tsx, src/design/MsgBox.tsx, src/design/NewMsgInput.tsx, src/hooks/useAddressFromEns.ts
Closes #188
- fixed new message animation
- connected hooks, validation, loading states, input focus, sending message, navigating to dm page
- [notion](https://www.notion.so/relaycc/Messages-Page-ea3a564281304ba295f68be90c2459ef#fb8df6b225b74330b08cf51425af0f68)
- [loom video](https://www.loom.com/share/fceee8de04b949578e97a694e0d505ce)
=> feat: 🎸 add new message page logic

src/components/Avatar.tsx, src/components/DirectMessagesPage.tsx, src/components/MessagesPage.tsx, src/components/NewMessage.tsx, src/design/ArrowUpCircle.tsx, src/design/Avatar.tsx, src/design/ENSName.tsx, src/design/MessagePreview.tsx, src/design/MsgBox.tsx, src/design/MsgBundles.tsx, src/design/Skeleton.tsx
Closes #300
- fixed direct message page design issues and added loading skeletons
- [loom video](https://www.loom.com/share/fe3e269bf6634367860335336f44b403)
=> fixed comp.  and page according to Aaron's issue

src/components/RequestsPage.tsx, src/pages/receiver/requests.tsx
Closes #303
Created a semi interactive request page without logic implemented. 
Once we have the appropriate hooks and functions to use figured out it would not be much of a hassle to wire this in.
=> Request page placeholder

src/components/ChatsPreview.tsx, src/components/MessagesPage.tsx, src/components/RequestPreview.tsx, src/components/RequestsPage.tsx, src/design/Checkbox.tsx, src/design/MessagePreview.tsx, src/design/Request.tsx, src/hooks/useReadWriteValue.ts
Closes #314
- added `useReadWriteValue` hook to handle ignore/accept/unignore conversations, and fetching ignored/accepted/requested conversations
- connected new hook to requests/messages pages
- [loom video](https://www.loom.com/share/2da0f4d3e0444b63918bdd0956495c82)
=> feat: 🎸 add request page logic

src/design/Loader.tsx, src/pages/design/index.tsx
I added a loading component with animations used as close as possible to the figma design. Any suggestions are welcome. Here is a video of it with multiple component sizes. 
It's built in a way to when you use it, you put it in a container with the height and width and border radius of the element thats loading along with overflow:hidden
https://user-images.githubusercontent.com/81312527/214971679-9bf1fff9-7600-428c-b54f-f6a716ec5dc4.mov
=> Loader.tsx has been added to handle loading states

src/design/relay/Footer.tsx, src/design/relay/Logo.tsx
=> feat: 🎸 add footer responsiveness

src/design/relay/DirectoryCard.tsx, src/design/relay/DirectoryHeader.tsx, src/design/relay/MenuIcon.tsx, src/design/relay/Sidebar.tsx, src/design/typography.ts, src/pages/search/index.tsx
✅ Closes: #327
- [loom video](https://www.loom.com/share/b19d5815369c4eaa832de7762ac7a732)
- [another loom video](https://www.loom.com/share/0aaab789ad7e4a8690662499cb61261c)
=> feat: 🎸 add directory responsiveness

src/hooks/useReadWriteValue.ts
Fixes the messages and requests not showing up. However it seems not all the received messages show up in the direct message screen, and on the message screen ChatPreview, its not the last message in the conversation that shows up. This might be an issue specific to the conversation I tested with however. We should look into it/discuss it in discord.
Closes  #339
=> Messages and request bugs

src/components/RequestsPage.tsx
=> fix: 🐛 fix request page avatars

src/design/relay/Receiver.tsx
- ✅ Closes: https://github.com/relaycc/relay/issues/368
=> fix: 🐛 move receiver button/window bottom/righ 1rem

src/design/relay/DirectoryHeader.tsx, src/design/relay/Search.tsx, src/design/relay/Sidebar.tsx, src/pages/search/index.tsx
[loom](https://www.loom.com/share/266b5a855f3e4bf6b242cca8b35d50b4)
- Closes #354
- added new breakpoints
- added category row
- added sidebar overlay
=> fix: 🐛 add breakpoints, dir header, sidebar overlay, category

src/components/DirectMessagesPage.tsx, src/design/MsgBundles.tsx, src/design/MsgPreview.tsx, src/lib/getDisplayDate.ts
=> DM page css issues and timestamps improvement

src/pages/_app.tsx, src/styles/baseStyles.css
[_link to a video showcasing the bugfix_](https://www.loom.com/share/f4311617944145eaa56a824b00737235)
- ✅ Closes: #414
=> fix: 🐛 fix FOUT
